# Generated by Django 3.2.5 on 2022-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220318_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/images/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entry/images/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='entry/files/'),
        ),
    ]
